#!/usr/bin/env python3
"""Generate Forever's encounter reference from a specific wago.tools build.

python .github/scripts/generate-forever-encounters.py --build 1.60.1.69913

For offline generation, pass --csv-dir containing DungeonEncounter.csv and Map.csv
exported from that build. Review the instance selection when updating the build;
client tables retain test maps and SoD content, so not every row belongs here.
"""

import argparse
import csv
import io
import json
from pathlib import Path
import re
from urllib.request import urlopen


# Reviewed against LFGDungeons in 1.60.1.69913. Its MapID column is unpopulated,
# so keep explicit map IDs instead of attempting fuzzy name matching.
# Shared maps (Dire Maul, Blackrock Spire, Scarlet Monastery) include all wings.
# https://wago.tools/db2/LFGDungeons/csv?build=1.60.1.69913
DUNGEONS = (
    389, 36, 43, 33, 34, 48, 90, 47, 189, 129, 70, 209, 349, 109,
    230, 229, 429, 289, 329,
    2959, 2998, 2999, 3065,  # Dalaran, Wetlands, Lordaeron, Hall of Thanes
)
# Preserve the classic raid/world-boss reference scope. AQ and Naxxramas are
# missing from the old LFG catalog but remain in Map and DungeonEncounter.
RAIDS = (249, 409, 469, 309, 509, 531, 533, 2789, 2791)
# Difficulty lists both 1 and 201 as five-player Normal. Keep their distinct
# encounter IDs together; don't guess which version the server will report.
# 0 applies to all difficulties. Exclude the SoD 10/20-player variants.
# https://wago.tools/db2/Difficulty/csv?build=1.60.1.69913
DUNGEON_DIFFICULTIES = {0, 1, 201}
EXCLUDED_ENCOUNTERS = {3018}  # The Molten Core: extra SoD encounter
OUTPUT = Path(__file__).resolve().parents[2] / "M33kAuras" / "Encounters_Forever.lua"


def source_url(table, build):
    return f"https://wago.tools/db2/{table}/csv?build={build}"


def read_table(table, build, csv_dir):
    if csv_dir:
        text = (csv_dir / f"{table}.csv").read_text(encoding="utf-8-sig")
    else:
        with urlopen(source_url(table, build), timeout=30) as response:
            text = response.read().decode("utf-8-sig")
    reader = csv.DictReader(io.StringIO(text))
    required = {"ID", "MapName_lang", "InstanceType"} if table == "Map" else {
        "ID", "Name_lang", "MapID", "DifficultyID", "OrderIndex",
    }
    if not required.issubset(reader.fieldnames or []):
        raise ValueError(f"{table}: missing CSV columns {sorted(required)}")
    return list(reader)


def collect_groups(encounters, maps):
    maps = {int(row["ID"]): row for row in maps}
    selected = {map_id: [] for map_id in (*DUNGEONS, *RAIDS)}
    seen = set()
    for row in encounters:
        encounter_id, map_id = int(row["ID"]), int(row["MapID"])
        if encounter_id in seen:
            raise ValueError(f"Duplicate encounter ID: {encounter_id}")
        seen.add(encounter_id)
        if map_id not in selected or encounter_id in EXCLUDED_ENCOUNTERS:
            continue
        if map_id in DUNGEONS and int(row["DifficultyID"]) not in DUNGEON_DIFFICULTIES:
            continue
        selected[map_id].append(row)

    groups = []
    for map_id, rows in selected.items():
        map_info = maps.get(map_id)
        expected_type = 1 if map_id in DUNGEONS else 2
        if not map_info or int(map_info["InstanceType"]) != expected_type:
            raise ValueError(f"Review missing or reclassified map {map_id}")
        if not rows:
            raise ValueError(f"No encounters for selected map {map_id}")
        bosses = {}
        for row in sorted(rows, key=lambda row: (int(row["OrderIndex"]), int(row["ID"]))):
            name = row["Name_lang"].strip()
            if not name:
                raise ValueError(f"Encounter {row['ID']} has no name")
            bosses.setdefault(name, []).append(int(row["ID"]))
        groups.append((map_id, map_info["MapName_lang"], bosses))
    return groups


def lua_string(text):
    # JSON's printable string escaping is also valid for these Lua strings.
    if any(ord(char) < 32 for char in text):
        raise ValueError("Unexpected control character in an encounter/map name")
    return json.dumps(text, ensure_ascii=False)


def render(groups, build):
    lines = [
        "-- Generated by .github/scripts/generate-forever-encounters.py; do not edit by hand.",
        f"-- Forever build: {build}",
        f"-- {source_url('DungeonEncounter', build)}",
        f"-- {source_url('Map', build)}",
        "if not M33kAuras.IsLibsOK() or not M33kAuras.IsForever() then return end",
        "local _, Private = ...",
        "local L = M33kAuras.L",
        "",
        "function Private.BuildForeverEncounterLists()",
        "  return {",
    ]
    for map_id, name, bosses in groups:
        lines.append(f"    [{map_id}] = {{")
        lines.append(f"      name = L[{lua_string(name)}],")
        instance_type = "raid" if map_id in RAIDS else "party"
        lines.append(f'      instanceType = "{instance_type}",')
        lines.append("      encounters = {")
        for boss, ids in bosses.items():
            for encounter_id in sorted(ids):
                lines.append(f'        {{{encounter_id}, L[{lua_string(boss)}]}},')
        lines.extend(["      },", "    },"])
    lines.extend([
        "  }",
        "end",
        "",
    ])
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--build", required=True, help="Exact Forever build, e.g. 1.60.1.69913")
    parser.add_argument("--csv-dir", type=Path, help="Read local exports instead of downloading")
    parser.add_argument("--output", type=Path, default=OUTPUT)
    args = parser.parse_args()
    if not re.fullmatch(r"1\.60\.\d+\.\d+", args.build):
        parser.error("Expected a Forever 1.60.x build")
    encounters = read_table("DungeonEncounter", args.build, args.csv_dir)
    maps = read_table("Map", args.build, args.csv_dir)
    groups = collect_groups(encounters, maps)
    args.output.write_text(render(groups, args.build), encoding="utf-8", newline="\n")
    count = sum(len(ids) for _, _, bosses in groups for ids in bosses.values())
    print(f"Wrote {count} encounter IDs across {len(groups)} maps to {args.output}")
    omitted_maps = sorted({int(row["MapID"]) for row in encounters} - set(DUNGEONS) - set(RAIDS))
    map_names = {int(row["ID"]): row["MapName_lang"] for row in maps}
    print("Maps omitted for review: " + ", ".join(f"{mid} ({map_names.get(mid, '?')})" for mid in omitted_maps))


if __name__ == "__main__":
    main()
